# Erstes Beispiel
## Module einbinden

In [ ]:
import pandas as pd

In [ ]:
dfKerg=pd.read_excel('rawData/KlausurPunkte.xlsx', header=4, usecols='A:L')
dfKerg

           Name   A1   A2   A3   A4    A5   A6   A7   A8   A9  A10   A11
0     Alexander  4.0  6.0  4.0  7.0  11.0  4.0  4.0  5.0  5.0  4.5  10.5
1         Andre  4.0  3.5  4.0  8.0  20.5  4.0  3.0  3.5  3.5  3.0   4.0
2        Celine  4.0  3.5  2.0  7.0  13.5  5.0  5.0  5.0  4.5  5.0  11.0
3     Christian  3.5  2.5  1.0  6.5  17.0  2.5  5.0  5.0  4.0  6.0   4.0
4   Christopher  3.5  0.5  0.0  4.0   7.5  0.0  0.0  0.0  0.0  0.0   0.0
5        Daniel  4.0  2.0  1.0  6.5  15.5  1.0  5.0  5.0  3.0  4.5  11.0
6         Felix  4.0  3.5  4.0  8.0  10.0  1.5  5.0  3.5  0.0  2.0   7.5
7          Finn  4.0  0.5  1.0  6.5  10.5  1.5  3.5  3.5  1.0  5.5   8.5
8       Florian  4.0  4.0  4.0  5.0  15.5  2.5  3.0  5.0  3.5  4.5   2.5
9           Jan  4.0  7.0  4.0  7.5  13.0  3.5  5.0  5.0  5.0  6.0   8.0
10       Jannik  4.0  2.0  3.5  5.5  10.5  5.0  5.0  5.0  3.0  0.0   2.0
11       Jannis  4.0  0.0  4.0  6.5  16.0  2.0  5.0  5.0  1.0  4.5   8.0
12      Jolante  4.0  6.0  4.0  7.0  15.0  4.5  5.0  5.0  5.0  6.0  12.0
13       Julian  4.0  5.0  4.0  7.0  13.0  1.0  1.5  0.0  3.0  6.0   2.0
14          Kai  2.5  2.5  4.0  7.0  15.5  5.0  5.0  5.0  2.0  3.0   9.5
15        Kamil  4.0  0.0  1.0  5.5   6.0  2.5  2.0  0.0  0.0  0.5   1.0
16        Lasse  4.0  5.0  4.0  6.5  16.5  4.0  5.0  5.0  3.5  6.0  13.5
17      Lennard  4.0  3.0  4.0  5.5  21.0  4.0  5.0  5.0  4.5  5.5  11.5
18         Lisa  4.0  4.0  4.0  7.0  19.0  0.0  3.5  5.0  1.5  0.0   0.0
19         Luca  4.0  3.5  4.0  7.0  14.0  3.5  1.5  5.0  4.5  5.0   7.5
20        Lukas  1.5  3.5  3.5  6.0   9.0  4.0  2.0  5.0  3.5  1.5   1.0
21        Mandy  4.0  0.0  4.0  5.5  16.5  2.0  2.0  4.0  3.0  3.5   1.0
22       Manuel  3.5  2.0  3.0  6.5  13.0  2.5  5.0  5.0  0.0  3.5  11.0
23       Marvin  4.0  3.0  1.0  7.0  10.5  4.0  5.0  3.5  1.0  4.5   8.0
24   Maximilian  4.0  4.5  1.0  5.5  17.5  5.0  4.0  5.0  4.0  6.0   9.0
25       Niklas  4.0  5.0  4.0  6.5   8.0  5.0  2.0  5.0  5.0  4.5   8.5
26       Pascal  4.0  0.0  3.0  7.0   8.5  5.0  1.5  3.0  0.0  4.0   9.5
27      Patrick  4.0  6.0  1.5  6.5  21.0  5.0  5.0  5.0  0.0  6.0   5.0
28        Robin  4.0  0.5  4.0  5.0  17.0  5.0  5.0  5.0  2.5  3.0  14.0
29        Roman  2.5  5.5  4.0  8.0  15.5  5.0  2.0  5.0  6.0  6.0   9.0
30        Simon  3.5  2.0  4.0  6.5  10.5  5.0  4.0  5.0  3.5  4.0  10.0
31      Susanne  4.0  6.0  4.0  8.0  22.0  5.0  3.5  5.0  6.0  6.0  11.0
32         Sven  4.0  5.5  2.5  7.0  12.0  5.0  5.0  5.0  3.0  6.0  13.0
33       Thomas  4.0  6.5  4.0  7.5  16.5  5.0  5.0  5.0  6.0  6.0  15.0
34          Tim  4.0  0.0  3.0  7.0  14.0  5.0  2.0  0.0  2.0  4.0   1.5
35       Tobias  4.0  0.0  1.0  7.0   9.0  0.0  4.0  5.0  3.5  3.0   3.5
36    Zacharias  4.0  1.0  4.0  2.5  10.0  0.0  2.0  1.5  1.0  1.5   0.0

In [ ]:
dfKerg['sumP'] = 0
dfKerg['sumP'] = df.sum(axis=1)

In [ ]:
dfKerg.iloc[[27],:]

       Name   A1   A2   A3   A4    A5   A6   A7   A8   A9  A10  A11   sumP
27  Patrick  4.0  6.0  1.5  6.5  21.0  5.0  5.0  5.0  0.0  6.0  5.0  130.0